<?php
define("PROJECT_TITLE","أم آند أي للبرمجيات");
define("Main","البداية");
define("News","الأخبار");
define("About","عن الشركة");
define("OurAccounts","حساباتنا");
define("Locations","الموقع الجغرافي");
define("JoinUs","ساهم معنا");
define("Gallery","معرض الصور");
define("ContactUs","اتصل بنا");
define("MailList","القائمة البريدية");
define("Members_Login","دخول الأعضاء");
define("Products","المنتجات");
define("Categories","التصنيفات");
define("Adv","الإعلانات");
define("Links","روابط مفيدة");
define("Maintenance","طلب صيانة");
 
define("Back","عودة");
define("Back_to_home","عودة إلى الرئيسية");
define("user_name","اسم المستخدم");
define("password","كلمة المرور");
define("Re-Type","أعد كتابة");
define("Sign_in","تسجيل دخول");
define("Edit","تحرير");
define("Delete","حذف");
define("nowandate", date("Y-m-d H:i:s"));
define("curdatetime", date("d-m-Y H:i:s"));
define("date", date("Y-m-d"));
define("delete_question", "هل تريد بالتأكيد حذف العنصر المسمى: %s ؟");
define("Save", "حفظ");
define("Send","إرسال");
define("more","المزيد");
define("NID","ID");
define("Hidden","إخفاء (لا يمكن للزوار معاينة هذا السجل)");
define("LastUpdate","آخر تحديث");
define("NDate","آخر تحديث");
define("Visits","عدد الزيارات");
define("lang","اللغة");
define("Related_Pages","صفحات ذات صلة");
define("Visitors","Visits");
define("View","تحميل الملف");
define("View_Orig_Page","عرض الصفحة الأصلية");
define("Home","الرئيسية");
define("Articles","المقالات");
define("Read_More","المزيد...");
define("Remove_Pic","حذف الصورة");
define("Comments","التعليقات");
define("aLinks","مراجع وروابط");
define("aPhotos","لقطات وصور");
define("admin_controls","لوحة التحكم");
define("Downlods","قسم التحميل");
define("Yes","نعم");
define("No","لا");
define("insrt_ur_eml","اشترك بالقائمة البريدية");
 
 
define("Visitor_EMail","البريد الإلكتروني");
 
define("CannotMasking", "فشل في إنشاء القناع!");
define("NotVerified", "يرجى إدخال الرمز بشكل صحيح أدناه!");
define("CannotResize", "فشل في تغيير حجم الصورة!");
define("ErrFileType", "Invalid File Type!");
define("CannotUpload", "خطأ أثناء رفع الملف!");
define("ReRegistered", "شكراً لك! تم إعادة تفعيل إشتراكك بنجاح..");
define("CancelRegister", "تم إلغاء إشتراكك بنجاح! شكراً لك.");
define("RegisteredOK", "شكراً لك! تم تسجيلك بنجاح...");
define("RowDeleted", "تم الحذف بنجاح!");
define("DBOK", "تم حفظ البيانات بنجاح!");
define("DBERR", "نأسف لحصول خطأ غيرمتوقع أثناء الكتابة إلى قاعدة البيانات! يرجى إعادة المحاولة لاحقاً...");
define("FillAllRequierd", "يجب إدخال جميع الحقول المطلوبة (*) !");
define("FillAll", "يجب إدخال جميع الحقول!");
define("DataIsExist", "البيانات موجودة.. يرجى إدخال بيانات جديدة!");
define("IsNotRegistered", "المعذرة! أنت غير مسجل لدينا سابقاً.");
define("Uploded", "تم رفع الملف بنجاح!");
define("Commented", "تم استقبال تعليقكم وشكرا لتواصلكم!");
define("InvalidTel", "الرجاء إدخال رقم<u>هاتف</u>صحيح! فقط الأرقام مسموحة..");
define("InvalidMob", "الرجاء إدخال رقم<u>فاكس</u>صحيح! فقط الأرقام مسموحة.");
define("InvalidFax", "الرجاء إدخال رقم<u>موبايل</u>صحيح! فقط الأرقام مسموحة.");
define("InvalidMail", "الرجاء إدخال<u>بريد إلكتروني</u>صحيح!");
define("You_can_contact_us_directly_by_filling_this_application", "للتواصل معنا مباشرة, الرجاء ملىء الاستمارة التالية!");
 
 
define("This_helps_us_to_prevent_automatic_registration","الرجاء إدخال المحارف الظاهرة أدناه في الصورة (غير حساس لحالة الأحرف)");
define("No_Rows_Selected","لايوجد نتائج");
 
define("Set_Def_Pic","تعيين الصور الإفتراضية");
//VCOMMENTS >>>
define("Search","بحث");
define("VComments","تعليقات الزوار");
define("VComment_Text","نص التعليق");
define("v_delete_question", "هل تريد بالتأكيد حذف التعليق: %s ؟");
define("Visitor_Name","الاسم");
//VCOMMENTS <<<
 
//NAVIGATOR >>>>>>>>>>>>>>>
define("dir", "rtl");
define("align","right");
define("r_align","left");
define("Next", "التالي");
define("Last", "الأخير");
define("First", "الأول");
define("Previous", "السابق");
define("rows_found", "نتيجة");
define("Page", "صفحة");
define("of", "من");
//END NAVIGATOR <<<<<<<<<<<
 
/////////////////////////////////////////////////////////////////////////////
 
define("Remember_Me","ابق متصلا على هذا الكمبيوتر");
define("Thanks_Your_email_was_sent","تم ارسال رسالتك بنجاح !!");
define("Sorry_Please_try_again_later","نأسف لحدوث خطأ .. الرجاء المحاولة لاحقاً");
/*****   mail list   *****/
define("Email_already_exists","ايميلك مسجل مسبقا");
define("Added_successfully","اضيف ايميلك بنجاح");
define("Adding_error","لقد حدث خطأ,حاول لاحقا");
 
define("Change_Password","تغيير كلمة السر");
define("Sign_UP","تسجيل حساب جديد");
define("Sign_In","تسجيل دخول");
define("Sign_Out","تسجيل خروج");
 
//Side Bar >>>
define("Our_Services","خدماتنا");
define("Our_Customers","زبائننا");
define("Download","التحميل");
define("FAQ","الأسئلة الشائعة");
define("Albums","ألبومات الصور");
define("Jobs","فرص عمل");
define("Pictures","صور الالبوم");
//Side Bar <<<
 
define("Latest_Products","آخر المنتجات");
define("Latest_News","آخر الأخبار");
define("All_Products","جميع المنتجات");
define("All_News","جميع الأخبار");
 
//Control_Panel >>>
define("Control_Panel","لوحة التحكم");
define("Users_Management","إدارة المستخدمين");
//Control_Panel <<<