<?php
//NEWS>>>
define("News", "الأخـبـار");
define("News_Title", "العنوان");
define("News_Summury", "الملخص");
define("News_Text", "النص");
define("News_Photo", "الصورة");
define("Back_to_News", "عودة");
define("Add_News", "إضافة خبر");
define("Edit_News","تحرير");
define("View_News","الأخبار");
define("Del_News","حذف");
define("News_LinkTo","ربط مع");
define("News_PopupLink","رابط الفيديو");
define("FileA","دفتر الشروط الحقوقي");
define("FileB","دفتر الشروط الفني");
define("HideOn","إخفاء بتاريخ");
define("Place","المكان");
//END NEWS<<<

//MSG>>>
define("C_Name", "الاسم");
define("C_Email", "E-Mail");
define("C_Mobile", "رقم الجوال");
define("C_Country", "البلد");
define("C_MText", "نص الرسالة");
define("Back_to_MSG", "عودة إلى قائمة الرسائل");
define("Add_MSG", "تواصل معنا");
define("Edit_MSG","تحرير الرسالة");
define("View_MSG","جدول الرسائل");
define("Del_MSG","حذف الرسالة");
define("QuickMenu","إظهار في القائمة السريعة");
define("C_Dept","إرسال إلى");
define("Location","الموقع على الخريطة");
//END MSG<<<

//ULINKS>>>
define("Link_Title", "عنوان الرابط");
define("NLink", "الرابط");
define("Link_Text","تعليق على الرابط");
define("Back_to_ULinks", "عودة إلى قائمة الروابط");
define("Add_ULinks", "رابط جديد");
define("Edit_ULinks","تحرير الرابط");
define("View_ULinks","الماركات");
define("Logo","اللوغو");
define("Useful_Links","روابط هامة");
define("Del_ULinks","حذف الرابط");
//END ULINKS<<<

//DEPT>>>
define("Edit_Dept","تحرير القسم");
define("Add_Dept","إدراج قسم");
define("View_Dept","أقسام الشركة");
define("Del_Dept","حذف قسم");
define("Dept_ar","القسم");
define("Dept_en","Department");
define("Email","البريد الإلكتروني");
define("Dept_ar","القسم (عربي)");
define("Dept_en","القسم (إنجليزي)");
//END DEPT<<

//Album>>>
define("Add_Album", "إضافة ألبوم");
define("Edit_Album", "تعديل ألبوم");
define("Album_Title_en", "عنوان الألبوم [en]");
define("Album_Title_ar", "عنوان الألبوم [ar]");
define("View_Album","معرض الصور");
define("View_Albums","معرض الصور");
define("Del_Album","حذف ألبوم");
define("Albums","ألبومات");
//End Album<<<

//Pic>>>
define("Add_Pic", "إضافة صورة");
define("Edit_Pic", "تعديل صورة");
define("Pic", "الصورة");
define("Video","فيديو [FLV]");
define("Pic_Title_en", "عنوان الصورة [en]");
define("Pic_Title_ar", "عنوان الصورة [ar]");
define("View_Pic","عرض صورة");
define("Del_Pic","حذف صورة");
define("Album_Name", "الألبوم");
define("View_Albums","عرض الألبومات");
define("IsMainPic","الصورة الإفتراضية");
//End Pic<<<

//USERS>>>
define("Edit_User","تحرير بيانات المستخدم");
define("Add_User","اشتراك");
define("View_User","المستخدمون");
define("Del_User","حذف مستخدم");
define("UName","الاسم الكامل");
define("UserName","البريد الإلكتروني");
define("upass","كلمة المرور");
define("Country","الدولة");
define("UTel","الهاتف");
define("UFax","الفاكس");
define("UAddress","العنوان");
//END USERS<<<

//Cats >>>>>>>>>>>>>>>
define("Edit_Cats","تحرير التصنيف");
define("Add_Cats","إضافة تصنيف");
define("View_Cats","عرض التصنيفات");
define("Del_Cats","حذف تصنيف");
define("cat_title_en","التصنيف(en)");
define("cat_title_ar","التصنيف(ar)");
//END Cats <<<<<<<<<<<

//Products >>>>>>>>>>>>>>>
define("Edit_Products","تعديل منتج");
define("Add_Products","إضافة منتج");
define("View_Products","المنتجات");
define("Del_Products","حذف منتج");
define("cat_id","التصنيف");
define("prod_title","عنوان المنتج");
define("prod_summary","ملخص المنتج");
define("prod_text","مطول المنتج");
define("prod_lang","لغة المنتج");
define("prod_pic","الصورة");
//END Products <<<<<<<<<<<

//ADS>>>
define("Edit_Ads","تحرير الإعلان");
define("Add_Ads","إدراج إعلان");
define("View_Ads","إدارة الإعلانات");
define("Del_Ads","حذف إعلان");
define("Ads_NTitle","عنوان الإعلان");
define("Ads_File","الملف (JPG or SWF)");
define("Ads_NLink","الرابط");
define("Ads_NWhere","المكان");
define("Ads_NWidth","العرض [SWF]");
define("Ads_NHeight","الطول [SWF]");
define("at_first","أولاً");
define("at_second","ثانيا");
define("at_third","ثالثا");
//END ADS<<<

