<?php
//NEWS>>>
define("News", "News");
define("News_Title", "Title");
define("News_Summury", "Summury");
define("News_Text", "Text");
define("News_Photo", "Photo");
define("Back_to_News", "Back");
define("Add_News", "Add Item");
define("Edit_News","Edit Item");
define("View_News","News");
define("Del_News","Remove Item");
define("News_LinkTo","Link to");
define("Album_Name","Album");
define("News_PopupLink","Video Link");
define("FileA","Legal Conditions Book");
define("FileB","Technical Conditions Book");
define("HideOn","Hide On");
define("Place","Place");
//END NEWS<<<

//Album>>>
define("Add_Album", "Add Album");
define("Edit_Album", "Edit Album");
define("Album_Title_en", "Album Title [en]");
define("Album_Title_ar", "Album Title [ar]");
define("Album_Title_so", "Album Title [so]");
define("ATitle_en","Album Title");
define("View_Album","Gallery");
define("Del_Album","Remove Albums");
define("Albums","Gallery");
//End Album<<<

//Pic>>>
define("Add_Pic", "Add Photo");
define("Edit_Pic", "Edit Photo");
define("Pic", "Photo");
define("Video","Video [FLV]");
define("Pic_Title_en", "Photo Title [en]");
define("Pic_Title_ar", "Photo Title [ar]");
define("Pic_Title_so", "Photo Title [so]");
define("PTitle_en","Photo Title");
define("View_Pic","Photos");
define("Del_Pic","Remove Photo");
define("Album_Name", "Album");
define("View_Albums","Albums");
define("IsMainPic","Main Photos");
//End Pic<<<

//Contactus>>>
define("Add_MSG", "Send Message");
define("Edit_MSG", "Edit Message");
define("View_MSG", "Inbox");
define("Del_MSG","Delete Message");
define("C_Name", "Name");
define("C_Mobile", "Mobile");
define("C_Email", "E-Mail");
define("C_Country", "Country");
define("C_MText", "Your Request");
define("C_Dept","Send To");
define("TargetMarket","Target Market Sector");
define("PPosition","Position in Organisation");
define("Company","Company");
define("Tel","Tel");
define("Location","Location on Google map");
define("C_Address","Address");
define("Export","Export");
define("Import","Import");
//END Contactus<<<

//DEPT>>>
define("Edit_Dept","Edit Department");
define("Add_Dept","Add Department");
define("View_Dept","Departments");
define("Del_Dept","Remove Department");
define("Dept_ar","القسم");
define("Dept_en","Department");
define("Email","E-Mail");
define("Dept_ar","Department [ar]");
define("Dept_en","Department [en]");
//END DEPT<<<

//ULINKS>>>
define("Link_Title","Link Title");
define("NLink", "Link");
define("Link_Text","Comment");
define("Back_to_ULinks", "Useful Links");
define("Add_ULinks", "Add Link");
define("Edit_ULinks","Edit Link");
define("View_ULinks","Trade Marks");
define("Logo","Logo");
define("Useful_Links","Useful Links");
define("Del_ULinks","Remove Links");
define("LClass","Class");
//END ULINKS<<<

//USERS>>>
define("Edit_User","Edit User");
define("Add_User","Add User");
define("View_User","Users");
define("Del_User","Remove User");
define("UName","Full Name");
define("UserName","User Name");
define("upass","Password");
define("Country","Country");
define("UTel","Tel");
define("UFax","Fax");
define("UAddress","Address");
//END USERS<<<

//Cats >>>>>>>>>>>>>>>
define("Edit_Cats","تحرير التصنيف");
define("Add_Cats","إضافة تصنيف");
define("View_Cats","عرض التصنيفات");
define("Del_Cats","حذف تصنيف");
define("cat_title_en","التصنيف(en)");
define("cat_title_ar","التصنيف(ar)");
//END Cats <<<<<<<<<<<

//Products >>>>>>>>>>>>>>>
define("Edit_Products","تعديل منتج");
define("Add_Products","Add Products");
define("View_Products","View Products");
define("Del_Products","Del Products");
define("cat_id","التصنيف");
define("prod_title","عنوان المنتج");
define("prod_summary","ملخص المنتج");
define("prod_text","مطول المنتج");
define("prod_lang","لغة المنتج");
define("prod_pic","الصورة");
//END Products <<<<<<<<<<<

//ADS>>>
define("Edit_Ads","Edit Ads");
define("Add_Ads","Add Ads");
define("View_Ads","View Ads");
define("Del_Ads","Delete Ads");
define("Ads_NTitle","Ads Title");
define("Ads_File","File (JPG or SWF)");
define("Ads_NLink","Link");
define("Ads_NWhere","Where");
define("Ads_NWidth","Width [SWF]");
define("Ads_NHeight","Height [SWF]");
//END ADS<<<

