<?php
define("Edit_x","تعديل");
define("Add_x","إضافة جديد");
define("View_x","جميع ");
define("Del_x","حذف");
define("ID_x","المعرف");
 
//ADS>>>
define("Ads","الاعلانات");
define("ads_id","معرف الإعلان");
define("ads_title_x","ads_title_ar");
define("ads_title_ar","الاعلان-عربي");
define("ads_title_en","الإعلان-EN");
define("ads_start","تاريخ البدء");
define("ads_end","تاريخ الانتهاء"); 
define("ads_link","الرابط");
define("ads_pic","صورة");
define("NDate","تاريخ الاضافة");
//END ADS<<<<<<<<<<<<<<<<<<<<<<<
 
//ALBUM>>>
define("Add_Album","إضافة ألبوم");
define("Edit_Album","تحرير الالبوم");
define("Delete_Album","حذف الالبوم");
define("View_Album","عرض الألبوم");
 
define("Album","الالبومات");
define("album_id","معرف الالبوم");
define("album_title_x","album_title_ar");
define("album_title_ar","عنوان الالبوم-عربي");
define("album_title_en","عنوان الالبوم-EN");
define("album_pic","album_title_ar");
define("NVnom","عدد الزيارات");
//END ALBUM<<<<<<<<<<<<<<<<<<<<<<<
 
//BUY_CONTRACT>>>
define("BConts","عقود البيع");
define("bcont_dist","الموزع");
define("bcont_cust","الزبون");
define("NSerial","التسلسلي");
define("bcont_prod","المنتج/المنتجات");
define("bcont_discount","التخفيض");
define("bcont_payment","المدفوع");
define("bcont_seen","تمت قراءته");
define("bcont_license","الترخيص");
//END BUY_CONTRACT<<<<<<<<<<<<<<<<<<<<<<<
 
//CATEGORY>>>
define("cat_id","معرف التصنيف");
define("cat_title_ar","التصنيف-عربي");
define("cat_title_en","التصنيف-EN");
define("cat_title_x","cat_title_ar");
//END CATEGORY<<<<<<<<<<<<<<<<<<<<<<<
 
//CONTACTUS>>>
define("cu_id","المعرف");
define("cu_name","شركتنا");
define("cu_mobile","جوال");
define("cu_job","عمل شركتنا");
define("cu_tel","هاتف");
define("cu_company","الرسالة");
define("cu_email","أيميل"); 
define("cu_pic","صورة");
//END CONTACTUS<<<<<<<<<<<<<<<<<<<<<<<
 
//FAQ>>>
define("FAQ","الاسئلة الشائعة");
define("faq_title_x","faq_title_ar");
define("faq_title_ar","السؤال");
define("faq_title_en","السؤال-EN");
define("faq_desc_ar","شرح-عربي");
define("faq_desc_en","شرح-EN");
//END FAQ<<<<<<<<<<<<<<<<<<<<<<<
 
//JOB>>>
define("job_title_x","job_title_ar");
define("job_title_ar","فرصة العمل-عربي");
define("job_title_en","فرصة العمل-EN");
define("job_desc_ar","الوصف");
define("job_desc_en","الوصف-EN");
//END JOB<<<<<<<<<<<<<<<<<<<<<<<
 
//MAINTENANCE_CONTRACT>>>
define("mconts","عقود الصيانة");
define("mcont_serial","تسلسلي صيانة");
define("mcont_dist","الموزع");
define("mcont_cust","الزبون");
define("bcont_serial","رقم عقد الشراء");
define("mcont_desc","وصف");
define("mcont_type","نوع العقد");
define("mcont_seen","تمت قراءته");
define("mcont_status","الحالة");
//END MAINTENANCE_CONTRACT<<<<<<<<<<<<<<<<<<<<<<<
 
//NEWS>>>
define("Add_News","إضافة خبر");
define("Edit_News","تعديل خبر");
define("Delete_News","حذف خبر");
define("View_News","الأخبار");
 
 
define("news_title_x","news_title_ar");
define("news_title_ar","الخبر");
define("news_title_en","الخبر-EN");
 
define("news_desc_x","news_desc_ar");
define("news_desc_ar","الوصف");
define("news_desc_en","الوصف-EN");
 
define("news_text_x","news_text_ar");
define("news_text_ar","نص مطول");
define("news_text_en","نص مطول-EN");
define("news_pic","صورة");
//END NEWS<<<<<<<<<<<<<<<<<<<<<<<
 
//PICTURE>>>Add_Pic
define("Add_Pic","اضافة صورة");
define("Edit_Pic","تحرير الصورة");
define("Delete_Pic","حذف االصورة");
define("View_Pic","عرض");
 
define("pic_album","الالبوم");
define("pic_title_x","pic_title_ar");
define("pic_title_ar","عنوان الصورة");
define("pic_title_en","عنوان الصورة-EN");
define("pic_ext","صورة");
define("pic_video","رابط فديو");
define("pic_is_main","صورة الالبوم؟");
//END MSG<<<<<<<<<<<<<<<<<<<<<<<
 
//PRODUCT>>>
define("Add_Products","إضافة منتج");
define("Edit_Products","تعديل منتج");
define("Delete_Products","حذف منتج");
define("View_Products","المنتجات");
define("View_Downloads","التحميل");
 
define("prod_title_x","prod_title_ar");
define("prod_title_ar","المنتج");
define("prod_title_en","المنتج-EN");
define("prod_cat","التصنيف");
 
define("prod_desc_x","prod_desc_ar");
define("prod_desc_ar","وصف");
define("prod_desc_en","وصف-EN");
 
define("prod_text_x","prod_text_ar");
define("prod_text_ar","شرح");
define("prod_text_en","شرح-EN");
 
define("prod_pic","الصورة");
define("prod_only_dw","برنامج مساعد؟");
define("prod_exe","برنامج تنفيذي");
define("prod_price","السعر");
 
//END PRODUCT<<<<<<<<<<<<<<<<<<<<<<<
 
//UCOMMENT>>>
define("ucom_user","المستخدم");
define("ucom_text","التعليق");
define("ucom_from_ip","عنوان آي بي");
define("ucom_reported","عدد الشكاوي");
//END UCOMMENT<<<<<<<<<<<<<<<<<<<<<<<
 
//USER>>>
 
define("Add_Users","إضافة");
define("Edit_Users","تعديل ");
define("Delete_Users","حذف ");
define("View_Users","جميع المستخدمين");
 
define("user_name","اسم المستخدم");
define("user_password","كلمة السر");
define("user_email","الايميل");
define("user_phone","هاتف");
define("user_address","عنوان");
define("user_country","الدولة");
define("user_city","المدينة");
define("user_birthyear","سنة الميلاد");
define("user_pic","صورة");
define("user_cat","نمط المستخدم");
define("Customer_Name","الزبون");
define("Distributor_Name","الموزع");
define("Employee_Name","الموزع");
define("Add_Customer","اضافة زبون");
define("View_Customer","الزبون");
 
define("employee","employee");
define("customer","customer");
define("distributor","distributor");
define("admin","admin");
//END USER<<<<<<<<<<<<<<<<<<<<<<<
 
//USER_CONFIG>>>
define("Configs","الاعدادات");
define("usrconf_user","المستخدم");
define("usrconf_color","اللون");
//END USER_CONFIG<<<<<<<<<<<<<<<<<<<<<<<
 
//VIDEO>>>
define("vid_title_ar","عنوان");
define("vid_title_en","عنوان-EN");
define("vid_desc_ar","وصف");
define("vid_desc_en","وصف-EN");
define("vid_link","الرابط");
//END VIDEO<<<<<<<<<<<<<<<<<<<<<<<
 
//SERVICE>>>
define("Services","الخدمات");
define("Edit_service","تعديل");
define("Add_service","اضافة خدمات");
define("View_service","خدماتنا");
define("Del_service","حذف خدمة");
define("srv_id","المعرف");
define("srv_title_ar","العنوان");
define("srv_title_en","العنوان-EN");
define("srv_desc_ar","الوصف");
define("srv_desc_en","الوصف-EN");
define("NVNom","عدد الزيارات");
define("NDate","تاريخ الاضافة");
//END SERVICE<<<<<<<<<<<<<<<<<<<<<<<
 
//groups>>>
define("Edit_groups","تعديل المجموعات");
define("Add_groups","اضافة مجموعة");
define("View_groups","مجموعات المستخدمين");
define("Del_groups","حذف مجموعة");
define("group_id","معرف");
define("group_name","اسم المجموعة");
//END groups<<<<<<<<<<<<<<<<<<<<<<<
 
//user_groups>>>
define("Edit_user_groups","تعديل مجموعات المستخدم");
define("Add_user_groups","اضافة مجموعة للمستخدم");
define("View_user_groups","عرض مجموعات المستخدم");
define("Del_user_groups","حذف مجموعة");
define("user_id","المستخدم");
define("user_group_id","مجموعة");
//END user_groups<<<<<<<<<<<<<<<<<<<<<<<
 
//user_privs>>>
define("Edit_user_privs","تعديل مجموعات المستخدم");
define("Add_user_privs","اضافة مجموعة للمستخدم");
define("View_user_privs","عرض مجموعات المستخدم");
define("Del_user_privs","حذف مجموعة");
define("user_id","المستخدم");
define("user_priv","مجموعة");
define("user_grant","يستطيع منحا لمستخدم آخر؟");
//END user_privs<<<<<<<<<<<<<<<<<<<<<<<
 
//user_group_privs>>>
define("Edit_user_group_privs","تعديل صلاحيات المجموعة");
define("Add_user_group_privs","اضافة صلاحية للمجموعة");
define("View_user_group_privs","صلاحيات المجموعة");
define("Del_user_group_privs","حذف صلاحية من المجموعة");
define("group_id","المجموعة");
define("priv","صلاحية");
//END user_group_privs<<<<<<<<<<<<<<<<<<<<<<<
 
//MSG>>>
define("BlockedIPs","العناوين المحجوبة");
//END MSG<<<<<<<<<<<<<<<<<<<<<<<